spring:
#数据库连接信息
  datasource:
#主数据源，默认的
    url: jdbc:log4jdbc:mysql://182.92.237.158:3307/zxx_admin?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&rewriteBatchedStatements=true
    username: zxx
    password: zxx@123
 
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

  