server:
 port: 9899

spring:
   profiles:
     active: test
     
   application:
     name: admin-sdk-test
     
eureka:
  instance:
    non-secure-port: ${server.port:8064}
#hystrix.command.default.execution.timeout.enabled: false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 10000
  ReadTimeout: 60000



